name = "hicm-space"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "hicm-space-db"
database_id = "23724224-ccf0-4114-9220-7f35f06d6fdd"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "hicm-space-storage"

[[queues.producers]]
binding = "THESIS_QUEUE"
queue = "hicm-space-thesis-queue"

